services:
  - type: web
    name: ai-interview-bot
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: ai-interview-bot
          property: port
    autoDeploy: true
    repo: https://github.com/your-username/ai-interview-bot.git
    branch: main